In [2]:
import numpy
em_list = []
def divisor(n):
    assert n>=0 and int(n) == n, "The number should be non-negative"
    if n==0:
        return 0
    else:
        for i in range(n):
            em_list.append(i+1)
            print(em_list)
            

    myArray = numpy.array(em_list)
    myInt = 5
    newArray = myInt//myArray
    
    return newArray
    
divisor(5)


[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 5]


array([5, 2, 1, 1, 1], dtype=int32)

In [ ]:
import numpy
em_list = []

def divisor(n):
    assert n>=0 and int(n) == n, "The number should be non-negative"
    if n==0:
        return None
    else:
        for i in range(n):
            em_list.append(i)
        myArray = numpy.array(em_list)
#         print(n//myArray)
        
        f = n//myArray
        
        emt = list(f)
        
        
        
        for i in emt:
            k = i//emt
            print(k)
            
            
            
            
            
    
            
    return divisor(n)
        
    

divisor(5)

C:\Users\manda\anaconda3\envs\cv\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in floor_divide
  
C:\Users\manda\anaconda3\envs\cv\lib\site-packages\ipykernel_launcher.py:21: RuntimeWarning: divide by zero encountered in floor_divide


[0 0 0 0 0]
[0 1 2 5 5]
[0 0 1 2 2]
[0 0 0 1 1]
[0 0 0 1 1]
[0 0 0 0 0 0 0 0 0 0]
[0 1 2 5 5 0 1 2 5 5]
[0 0 1 2 2 0 0 1 2 2]
[0 0 0 1 1 0 0 0 1 1]
[0 0 0 1 1 0 0 0 1 1]
[0 0 0 0 0 0 0 0 0 0]
[0 1 2 5 5 0 1 2 5 5]
[0 0 1 2 2 0 0 1 2 2]
[0 0 0 1 1 0 0 0 1 1]
[0 0 0 1 1 0 0 0 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 2 5 5 0 1 2 5 5 0 1 2 5 5]
[0 0 1 2 2 0 0 1 2 2 0 0 1 2 2]
[0 0 0 1 1 0 0 0 1 1 0 0 0 1 1]
[0 0 0 1 1 0 0 0 1 1 0 0 0 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 2 5 5 0 1 2 5 5 0 1 2 5 5]
[0 0 1 2 2 0 0 1 2 2 0 0 1 2 2]
[0 0 0 1 1 0 0 0 1 1 0 0 0 1 1]
[0 0 0 1 1 0 0 0 1 1 0 0 0 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 2 5 5 0 1 2 5 5 0 1 2 5 5]
[0 0 1 2 2 0 0 1 2 2 0 0 1 2 2]
[0 0 0 1 1 0 0 0 1 1 0 0 0 1 1]
[0 0 0 1 1 0 0 0 1 1 0 0 0 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 2 5 5 0 1 2 5 5 0 1 2 5 5 0 1 2 5 5]
[0 0 1 2 2 0 0 1 2 2 0 0 1 2 2 0 0 1 2 2]
[0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1]
[0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [1]:
# Python Program to find the length of
# substring with maximum difference of
# zeroes and ones in binary string.
MAX = 100

# Return true if there all 1s
def allones(s, n):
	
	# Checking each index
	# is 0 or not.
	co = 0
	
	for i in s:
		co += 1 if i == '1' else 0

	return co == n

# Find the length of substring with
# maximum difference of zeroes and
# ones in binary string
def findlength(arr, s, n, ind, st, dp):
	
	# If string is over
	if ind >= n:
		return 0

	# If the state is already calculated.
	if dp[ind][st] != -1:
		return dp[ind][st]

	if not st:
		dp[ind][st] = max(arr[ind] +
		findlength(arr, s, n, ind + 1, 1, dp),
			(findlength(arr, s, n, ind + 1, 0, dp)))
	else:
		dp[ind][st] = max(arr[ind] +
		findlength(arr, s, n, ind + 1, 1, dp), 0)
		
	return dp[ind][st]

# Returns length of substring which is
# having maximum difference of number
# of 0s and number of 1s
def maxLen(s, n):
	
	# If all 1s return -1.
	if allones(s, n):
		return -1

	# Else find the length.
	arr = [0] * MAX
	for i in range(n):
		arr[i] = 1 if s[i] == '0' else -1

	dp = [[-1] * 3 for _ in range(MAX)]
	return findlength(arr, s, n, 0, 0, dp)

# Driven Program
s = "11000010001"
n = 11
print(maxLen(s, n))

# This code is contributed by Ansu Kumari.


6


In [3]:
def sum_of_digit(n):
    assert n>=0 and int(n) == n, "The number should be non-negative"
    if n==0:
        return 0
    return int(n%10) + sum_of_digit(int(n/10))
    
sum_of_digit(126)

9

In [12]:
em=[]
def inas(n):
    for i in range(n):
        em.append(i)

    em_arr = numpy.array(em)
    
    print(em_arr/5)
    
    
inas(5)

[0.  0.2 0.4 0.6 0.8]


In [4]:
s = input()
n = len(s)
def fun(s):
    dp = [0] * len(s)
    dp[-1] = 1
    recentOccurence = {s[-1]: len(s) - 1}
    suffixSum = [0] * len(s)
    suffixSum[-1] = 1

    for i in range(len(s) - 2, -1, -1):
        if s[i] not in recentOccurence:
            dp[i] = (suffixSum[i + 1] + 1) % (10 ** 9 + 7)
            
        else:
            j = recentOccurence[s[i]]
            dp[i] = (suffixSum[i + 1] - suffixSum[j] + dp[j]) % (10 ** 9 + 7)
        
        suffixSum[i] = (suffixSum[i + 1] + dp[i]) % (10 ** 9 + 7)
        recentOccurence[s[i]] = i

    return suffixSum[0]

res = 0
for i in range(s-2):
    res += fun(s[i:i+n-2])
print(res)

 781484


TypeError: unsupported operand type(s) for -: 'str' and 'int'

In [ ]:
# Dictionary to store the number of coins to their corresponding keys 
array = {0:0,1:1}

def solve(n):
    if n in array:
        return array[n] #retruns the value of the key if found in array
    else:
        array[n] = max(n,solve(n//2)+solve(n//3)+solve(n//4))
        return array[n] 

if __name__ == '__main__':
    # taking the input 
    i = 10
    while(i > 0):
        n = int(input())
        print(solve(n))
        i -= 1

 13


13


 1


1


 1


1


 1


1


 1


1


 1


1


ValueError: invalid literal for int() with base 10: ''

In [15]:
# Python3 code to find elements whose
# frequency yis more than n/k
def morethanNbyK(arr, n, k) :
	x = n // k
	
	# unordered_map initialization
	freq = {}

	for i in range(n) :
		if arr[i] in freq :
			freq[arr[i]] += 1
		else :
			freq[arr[i]] = 1
		
	# Traversing the map
	for i in freq :
		
		# Checking if value of a key-value pair
		# is greater than x (where x=n/k)
		if (freq[i] > x) :
			
			# Print the key of whose value
			# is greater than x
			print(i)

# Driver code		
arr = [3,3 ]
n = len(arr)
k = 4

morethanNbyK(arr, n, k)

# This code is contributed by mohit kumar 29


3


In [ ]:
# Python3 code to find elements whose
# frequency yis more than n/k
def morethanNbyK(arr, n, k) :
	x = n // k
	
	# unordered_map initialization
	freq = {}

	for i in range(n) :
		if arr[i] in freq :
			freq[arr[i]] += 1
		else :
			freq[arr[i]] = 1
		
	# Traversing the map
	for i in freq :
		
		# Checking if value of a key-value pair
		# is greater than x (where x=n/k)
		if (freq[i] > x) :
			
			# Print the key of whose value
			# is greater than x
			print(i)

# Driver code		
arr = [ 1, 1, 2, 2, 3, 5, 4, 2, 2, 3, 1, 1, 1 ]
n = len(arr)
k = 4

morethanNbyK(arr, n, k)

# This code is contributed by mohit kumar 29
    

In [18]:
class Solution(object):
    def knightProbability(self, N, K, r, c):
        dp = [[0] * N for _ in xrange(N)]
        dp[r][c] = 1
        for _ in xrange(K):
            dp2 = [[0] * N for _ in xrange(N)]
            for r, row in enumerate(dp):
                for c, val in enumerate(row):
                    for dr, dc in ((2,1),(2,-1),(-2,1),(-2,-1),
                                   (1,2),(1,-2),(-1,2),(-1,-2)):
                        if 0 <= r + dr < N and 0 <= c + dc < N:
                            dp2[r+dr][c+dc] += val / 8.0
            dp = dp2

        return sum(map(sum, dp))


In [24]:
k = Solution(object)
k.knightProbability(3,3,1,5)

TypeError: object() takes no parameters

In [25]:
# Python3 code to find minimum steps to reach
# to specific cell in minimum moves by Knight
class cell:
	
	def __init__(self, x = 0, y = 0, dist = 0):
		self.x = x
		self.y = y
		self.dist = dist
		
# checks whether given position is
# inside the board
def isInside(x, y, N):
	if (x >= 1 and x <= N and
		y >= 1 and y <= N):
		return True
	return False
	
# Method returns minimum step to reach
# target position
def minStepToReachTarget(knightpos,
						targetpos, N):
	
	# all possible movements for the knight
	dx = [2, 2, -2, -2, 1, 1, -1, -1]
	dy = [1, -1, 1, -1, 2, -2, 2, -2]
	
	queue = []
	
	# push starting position of knight
	# with 0 distance
	queue.append(cell(knightpos[0], knightpos[1], 0))
	
	# make all cell unvisited
	visited = [[False for i in range(N + 1)]
					for j in range(N + 1)]
	
	# visit starting state
	visited[knightpos[0]][knightpos[1]] = True
	
	# loop until we have one element in queue
	while(len(queue) > 0):
		
		t = queue[0]
		queue.pop(0)
		
		# if current cell is equal to target
		# cell, return its distance
		if(t.x == targetpos[0] and
		t.y == targetpos[1]):
			return t.dist
			
		# iterate for all reachable states
		for i in range(8):
			
			x = t.x + dx[i]
			y = t.y + dy[i]
			
			if(isInside(x, y, N) and not visited[x][y]):
				visited[x][y] = True
				queue.append(cell(x, y, t.dist + 1))

# Driver Code	
if __name__=='__main__':
	N = 30
	knightpos = [1, 1]
	targetpos = [30, 30]
	print(minStepToReachTarget(knightpos,
							targetpos, N))
	
# This code is contributed by
# Kaustav kumar Chanda


20


In [18]:
ls = ['abcdefghijk','lsgs','svsa','sags','ahsfb','ndas','hgds','sdgb','nsgd','sg','sfd']
em_ls = []
# print(len(ls))
for i in ls:
#     print(i)
    em_ls.append(i)
print(em_ls)
    

['abcdefghijk', 'lsgs', 'svsa', 'sags', 'ahsfb', 'ndas', 'hgds', 'sdgb', 'nsgd', 'sg', 'sfd']


In [22]:
for i in range(10):
    print('i my',i)
    for j in range(i):
        print('together',i,j)

i my 0
i my 1
together 1 0
i my 2
together 2 0
together 2 1
i my 3
together 3 0
together 3 1
together 3 2
i my 4
together 4 0
together 4 1
together 4 2
together 4 3
i my 5
together 5 0
together 5 1
together 5 2
together 5 3
together 5 4
i my 6
together 6 0
together 6 1
together 6 2
together 6 3
together 6 4
together 6 5
i my 7
together 7 0
together 7 1
together 7 2
together 7 3
together 7 4
together 7 5
together 7 6
i my 8
together 8 0
together 8 1
together 8 2
together 8 3
together 8 4
together 8 5
together 8 6
together 8 7
i my 9
together 9 0
together 9 1
together 9 2
together 9 3
together 9 4
together 9 5
together 9 6
together 9 7
together 9 8


In [ ]:
def any_func(a,b):
    a = 
    

In [25]:
# from datetime import datetime
a = datetime.strptime("04:30",'%H:%M')
b = datetime.strptime("02:30",'%H:%M')
a


datetime.datetime(1900, 1, 1, 4, 30)

In [26]:
b

datetime.datetime(1900, 1, 1, 2, 30)

In [2]:
import datetime
a = datetime.timedelta(0, (4*3600+30*60))
b = datetime.timedelta(0, (2*3600+30*60))

c = a+b




datetime.timedelta(0, 25200)

In [3]:
# Python3 program to find highest
# power of 2 smaller than or
# equal to n.
def highestPowerof2(n):

	res = 0;
	for i in range(n, 0, -1):
		
		# If i is a power of 2
		if ((i & (i - 1)) == 0):
		
			res = i;
			break;
		
	return res;

# Driver code
n = 100;
print(highestPowerof2(n));
	
# This code is contributed by mits


64


In [4]:
# Python implementation to
# count number of ways to
# tile a floor of size n x m
# using 1 x m tiles

def countWays(n, m):
	
	# table to store values
	# of subproblems
	count =[]
	for i in range(n + 2):
		count.append(0)
	count[0] = 0
	
	# Fill the table upto value n
	for i in range(1, n + 1):
	
		# recurrence relation
		if (i > m):
			count[i] = count[i-1] + count[i-m]
		
		# base cases
		elif (i < m or i == 1):
			count[i] = 1

		# i = = m
		else:
			count[i] = 2
	
	
	# required number of ways
	return count[n]


# Driver code

n = 7
m = 4

print("Number of ways = ", countWays(n, m))

# This code is contributed
# by Anant Agarwal.


Number of ways =  5


In [6]:
def can_reach_end(nums):
    n = len(nums) - 1
    for i in range(n-1, -2, -1):
        if nums[i] + i >= n:
            n = i
    return n == 0
print(can_reach_end([1, 2,3]))

False


In [8]:
// Python Code

def sum_missing_duplicated(arr):
    arr.sort() # sort the list first
    missing = 0
    repeated = 0

    # Iterate from first index to last index
    for i in range(0, len(arr)):
        item = arr[i]
        isexist = False

        if not i + 1 in arr:
            missing = i + 1

        for j in range(i, len(arr) - 1):
            if item == arr[j + 1]:
                repeated = arr[i]
                
    return missing + repeated

# -------------------------

mylist = [1, 2, 2, 4, 5]
print("Answer is: " + str(sum_missing_duplicated(mylist)))

SyntaxError: invalid syntax (<ipython-input-8-5e43e4e7a0c4>, line 1)

In [9]:
x = 'cat'

def f():
    x = 'bird'
    def g():
        x = 'dog'
        y = 'fish'
        
        print(x)
    g()
f()

dog


In [11]:
=

SyntaxError: invalid syntax (<ipython-input-11-b00318e7ef2a>, line 1)

In [18]:
x =['1', '2','15', '-7','300']
y = sorted(x)
y

['-7', '1', '15', '2', '300']

In [37]:
def delete_1(items):
    i = 0
    while i < len(items):
        if len(items[i])==0:
            del items[i]
            
        i +=1
        
names = ['Rachel','','Meghana','','','Tim'];
delete_1(names)

In [38]:
def has_pos_neg(nums):
    has_pos = False
    has_neg = False
    
    for num in nums:
        has_pos = num>0
        has_neg = num<0
        
    return(has_pos,has_neg)

In [42]:
has_pos_neg([-1,0,1])

(True, False)

In [43]:
f = lambda n:1 if n<=1 else n*f(n-1)

g = f(4)

In [44]:
g

24

In [51]:
import queue
import threading
q = queue.Queue()

for i in [3,2,1]:
    def f():
        time.sleep(i)
        q.put(i)
    threading.thread(target=f).start()
    
print(q.get())

AttributeError: module 'threading' has no attribute 'thread'

In [2]:
k = []

In [3]:
for i in range(10):
#     print("i is",i)
    for j in range(i):
#         print("j is",j)
        
        k.append(j)
        print(k)
        
len(k)

[0]
[0, 0]
[0, 0, 1]
[0, 0, 1, 0]
[0, 0, 1, 0, 1]
[0, 0, 1, 0, 1, 2]
[0, 0, 1, 0, 1, 2, 0]
[0, 0, 1, 0, 1, 2, 0, 1]
[0, 0, 1, 0, 1, 2, 0, 1, 2]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2]
[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3]


45

In [4]:
print(k)

[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 8]
